name: Apply Supabase Migrations

on:
  push:
    branches: [main, master]
    paths:
      - "supabase/migrations/**"
      - "supabase/seed.sql"
      - ".github/workflows/supabase-db-migration.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Supabase CLI
        run: npm install supabase --save-dev

      - name: Set up Supabase CLI
        run: |
          echo "Configurando Supabase CLI..."
          npx supabase login --access-token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          npx supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Apply database migrations
        run: |
          echo "Aplicando migraciones de base de datos..."
          npx supabase db push

      - name: Apply seed data (Optional)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Aplicando datos de semilla (solo si se ejecuta manualmente)..."
          npx supabase db reset
